{% set name = "nba.stats" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0cdon build
  preserve_egg_dir: True

requirements:
  host:
    - python=3.7.7
    - psycopg2>=2.8.6
    - beautifulsoup4>=4.9.3
    - requests=2.24.0
    - scikit-learn=0.23.2
    - caritas.depot-core>=0.1.0
    - python-dateutil=2.8.1
  run:
    - python=3.7.7
    - psycopg2>=2.8.6
    - beautifulsoup4>=4.9.3
    - requests=2.24.0
    - scikit-learn=0.23.2
    - caritas.depot-core>=0.1.0
    - python-dateutil=2.8.1

test:
  imports:
    - nba.collector

  files:
    - tests/build_tests.py
