{ % set name = "nba.stats" % }
  { % set version = "0.0.1" % }

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0cdon build
  preserve_egg_dir: True

requirements:
  host:
    - python=3.11.7
    - psycopg2>=2.9.9
    - beautifulsoup4>=4.12.2
    - requests=2.31.0
    - scikit-learn=1.3.2
    - caritas.depot-core>=0.1.0
    - python-dateutil=2.8.2
  run:
    - python=3.11.7
    - psycopg2>=2.9.9
    - beautifulsoup4>=4.12.2
    - requests=2.31.0
    - scikit-learn=1.3.2
    - caritas.depot-core>=0.1.0
    - python-dateutil=2.8.2

test:
  imports:
    - nba.collector

  files:
    - tests/build_tests.py
